### ISSUE TITLE
Need for speed !

### ISSUE THREAD

**Issue by jjeremy40** [xyq7/InvCompress#7]
Hi,

Great work ! I'm currently using it in my phd research project. 

If I understand the code correctly, the context model (ctx_p) is significantly slowing down the entropy coding/decoding computation...

Is there any way to make this much faster ?

Thanks.

**Comment by xyq7** [comment]
Hi,

Thank you for your interest.  Yes, the context model we use is slow due to autoregressive computation. You can check the entropy coding w/o the context model such as "VARIATIONAL IMAGE COMPRESSION WITH A SCALE HYPERPRIOR". They will be much faster, but the performance is not good enough. 

Our work does not focus on entropy coding, but there are several works discussing this direction. I believe it is a quite promising topic. Welcome for further discussion.
